go:
    # Whenever the Go version is updated here, .travis.yml and
    # .circle/config.yml should also be updated if in use.
    version: 1.23
repository:
    path: github.com/prometheus/test-infra
build:
    binaries:
        - name: infra
          path: ./infra
        - name: tools/amGithubNotifier
          path: ./tools/amGithubNotifier
        - name: tools/commentMonitor
          path: ./tools/commentMonitor
        - name: tools/fake-webserver
          path: ./tools/fake-webserver
        - name: tools/scaler
          path: ./tools/scaler
        - name: tools/load-generator
          path: ./tools/load-generator
    flags: -a -tags netgo
crossbuild:
    platforms:
        - linux/amd64
