go:
    # Whenever the Go version is updated here, .travis.yml and
    # .circle/config.yml should also be updated if in use.
    version: 1.13
repository:
    path: github.com/prometheus/prombench
build:
    binaries:
        - name: prombench
          path: ./prombench/cmd/prombench
        - name: funcbench
          path: ./funcbench
        - name: tools/amGithubNotifier
          path: ./tools/amGithubNotifier
        - name: commentMonitor
          path: ./tools/commentMonitor
        - name: fake-webserver
          path: ./tools/fake-webserver
        - name: scaler
          path: ./tools/scaler
    flags: -a -tags netgo
crossbuild:
    platforms:
        - linux/amd64
