{
 "title": "Prometheus Benchmark - 2.3.x",
 "description": "Metrics useful for benchmarking and loadtesting Prometheus itself. Designed primarily for Prometheus 2.3.x.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Prometheus Version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_build_info{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - {{version}} - {{revision}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Uptime"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Max"
    },
    {
     "expr": "process_open_fds{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Open"
    }
   ]
  },
  {
   "title": "Head Time series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Time series"
    }
   ]
  },
  {
   "title": "Head Active Appenders",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Head Appenders"
    }
   ]
  },
  {
   "title": "Samples Appended/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - samples/s"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Chunks"
    }
   ]
  },
  {
   "title": "Head Chunks Created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Created"
    }
   ]
  },
  {
   "title": "Head Chunks Removed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Removed"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_min_time{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Min"
    },
    { "expr": "time() * 1000", "legendFormat": "Now" },
    {
     "expr": "prometheus_tsdb_head_max_time{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Max"
    }
   ]
  },
  {
   "title": "Head GC Time/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - GC Time/s"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Blocks Loaded"
    }
   ]
  },
  {
   "title": "TSDB Reloads/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Reloads"
    }
   ]
  },
  {
   "title": "WAL Fsync&Truncate Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Fsync Latency"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_tsdb_wal_trunacte_duration_seconds_count{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Truncate Latency"
    }
   ]
  },
  {
   "title": "TSDB Problems/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - WAL Corruptions"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Reload Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_not_found{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Head Series Not Found"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Compaction Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Retention Cutoff Failures"
    }
   ]
  },
  {
   "title": "Compactions/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Compactions"
    }
   ]
  },
  {
   "title": "Compaction Time/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}}"
    }
   ]
  },
  {
   "title": "Retention Cutoffs/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_total[10m])",
     "legendFormat": "{{prometheus}} - Retention Cutoffs"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_range_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_count{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Chunk Time Range"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Bytes/Sample",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Bytes/Sample"
    }
   ]
  },
  {
   "title": "First Compaction, Avg Chunk Samples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count{job=\"prometheus\",prometheus=~\"(test+).*\"}[10m])",
     "legendFormat": "{{prometheus}} - Chunk Samples"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Allocated"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[5m])",
     "legendFormat": "{{prometheus}} - 5m rate"
    }
   ]
  },
  {
   "title": "HTTP requests/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Query engine timings/s",
   "type": "graph",
   "description": "Time spent in each mode, per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - {{slice}}"
    }
   ]
  },
  {
   "title": "Rule group evaulation problems/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])  ",
     "legendFormat": "{{prometheus}} - Rule group missed"
    },
    {
     "expr": "rate(prometheus_rule_evaluation_failures_total{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Rule evals failed"
    }
   ]
  },
  {
   "title": "Evaluation time of rule groups/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_duration_seconds_sum{job=\"prometheus\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Rule evaluation duration"
    }
   ]
  },
  {
   "title": "Rule Group: $RuleGroup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "repeat": "RuleGroup",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_rule_group_interval_seconds{job=\"prometheus\",prometheus=~\"(test+).*\",rule_group=~\"$RuleGroup\"}\n",
     "legendFormat": "{{prometheus}} - Interval"
    },
    {
     "expr": "prometheus_rule_group_last_duration_seconds{job=\"prometheus\",prometheus=~\"(test+).*\",rule_group=~\"$RuleGroup\"}\n",
     "legendFormat": "{{prometheus}} - Last Duration"
    }
   ]
  }
 ]
}