projectid: {{ .GKE_PROJECT_ID }}
zone: {{ .ZONE }}
cluster:
  name: {{ .CLUSTER_NAME }}
  
  initialclusterversion: 1.25
  
  nodepools:
  # This node-pool will be used for running monitoring components
  - name: main-node
    initialnodecount: 1
    config:
      machinetype: n1-standard-4
      imagetype: COS_CONTAINERD
      disksizegb: 300
      labels:
        node-name: main-node
