{
 "title": "Prombench",
 "description": "Metrics useful for benchmarking and loadtesting Prometheus itself. Designed primarily for Prometheus 2.3.x.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RuleGroup",
    "query": "prometheus_rule_group_last_duration_seconds{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}"
   },
   { "name": "prombench-namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Benchmark - 2.3.x",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Version",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_build_info{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - {{version}} - {{revision}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Uptime"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Max"
      },
      {
       "expr": "process_open_fds{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Open"
      }
     ]
    },
    {
     "title": "Head Time series",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Time series"
      }
     ]
    },
    {
     "title": "Head Active Appenders",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Head Appenders"
      }
     ]
    },
    {
     "title": "Samples Appended/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - samples/s"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Chunks"
      }
     ]
    },
    {
     "title": "Head Chunks Created",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Created"
      }
     ]
    },
    {
     "title": "Head Chunks Removed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Removed"
      }
     ]
    },
    {
     "title": "Head Time Range",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "dateTimeAsIso" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_min_time{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Min"
      },
      { "expr": "time() * 1000", "legendFormat": "Now" },
      {
       "expr": "prometheus_tsdb_head_max_time{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Max"
      }
     ]
    },
    {
     "title": "Head GC Time/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - GC Time/s"
      }
     ]
    },
    {
     "title": "Blocks Loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Blocks Loaded"
      }
     ]
    },
    {
     "title": "TSDB Reloads/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Reloads"
      }
     ]
    },
    {
     "title": "WAL Fsync&Truncate Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Fsync Latency"
      },
      {
       "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Truncate Latency"
      }
     ]
    },
    {
     "title": "TSDB Problems/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_corruptions_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - WAL Corruptions"
      },
      {
       "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Reload Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_head_series_not_found{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Head Series Not Found"
      },
      {
       "expr": "rate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Compaction Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Retention Cutoff Failures"
      }
     ]
    },
    {
     "title": "Compactions/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compactions_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Compactions"
      }
     ]
    },
    {
     "title": "Compaction Time/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}}"
      }
     ]
    },
    {
     "title": "Retention Cutoffs/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Retention Cutoffs"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Time Range",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_range_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_range_count{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Chunk Time Range"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Bytes/Sample",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Bytes/Sample"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Samples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m]) / rate(prometheus_tsdb_compaction_chunk_samples_count{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[10m])",
       "legendFormat": "{{prometheus}} - Chunk Samples"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - RSS"
      },
      {
       "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Target heap size"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Next GC"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Allocated"
      }
     ]
    },
    {
     "title": "Allocations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Allocated Bytes/s"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Irate"
      },
      {
       "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[5m])",
       "legendFormat": "{{prometheus}} - 5m rate"
      }
     ]
    },
    {
     "title": "HTTP requests/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - {{handler}}"
      }
     ]
    },
    {
     "title": "HTTP request latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - {{handler}}"
      }
     ]
    },
    {
     "title": "Time spent in HTTP requests/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - {{handler}}"
      }
     ]
    },
    {
     "title": "Query engine timings/s",
     "type": "graph",
     "description": "Time spent in each mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - {{slice}}"
      }
     ]
    },
    {
     "title": "Rule group evaulation problems/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_iterations_missed_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])  ",
       "legendFormat": "{{prometheus}} - Rule group missed"
      },
      {
       "expr": "rate(prometheus_rule_evaluation_failures_total{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Rule evals failed"
      }
     ]
    },
    {
     "title": "Evaluation time of rule groups/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Rule evaluation duration"
      }
     ]
    },
    {
     "title": "Rule Group: $RuleGroup",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
     "repeat": "RuleGroup",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_rule_group_interval_seconds{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\",rule_group=~\"$RuleGroup\"}\n",
       "legendFormat": "{{prometheus}} - Interval"
      },
      {
       "expr": "prometheus_rule_group_last_duration_seconds{job=\"prometheus\",namespace=\"prombench-[[prombench-namespace]]\",prometheus=~\"(test+).*\",rule_group=~\"$RuleGroup\"}\n",
       "legendFormat": "{{prometheus}} - Last Duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{node}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"} - node_memory_MemFree_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"} - node_memory_Buffers_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"} - node_memory_Cached_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Free"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\",device!~'^(md\\\\\\\\d+$|dm-)'}[5m])",
     "legendFormat": "{{node}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{node=~'(test+).*',device!~'rootfs'})",
     "legendFormat": "{{node}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}[5m])",
     "legendFormat": "{{node}} - Context Switches"
    },
    {
     "expr": "irate(node_intr_total{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}[5m])",
     "legendFormat": "{{node}} - Interrupts"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\",fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Load 1m"
    },
    {
     "expr": "node_load5{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Load 5m"
    },
    {
     "expr": "node_load15{job=\"node-exporter\",namespace=\"prombench-[[prombench-namespace]]\",node=~\"(test+).*\"}",
     "legendFormat": "{{node}} - Load 15m"
    }
   ]
  }
 ]
}