# This file contains Kubernetes YAML files for the most important prow
# components. Don't edit resources in this file. Instead, pull them out into
# their own files.
---
apiVersion: v1
kind: Namespace
metadata:
  name: prow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow
  namespace: prow
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  namespace: prow
data:
  plugins: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: prow
data:
  config: |
    periodics:
    - interval: 10m
      agent: kubernetes
      name: echo-test
      spec:
        containers:
        - image: alpine
          command: ["/bin/date"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prowjobs.prow.k8s.io
  namespace: prow
spec:
  group: prow.k8s.io
  version: v1
  names:
    kind: ProwJob
    singular: prowjob
    plural: prowjobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            max_concurrency:
              type: integer
              minimum: 0
            type:
              type: string
              enum:
              - "presubmit"
              - "postsubmit"
              - "periodic"
              - "batch"
        status:
          properties:
            state:
              type: string
              enum:
              - "triggered"
              - "pending"
              - "success"
              - "failure"
              - "aborted"
              - "error"
          anyOf:
          - not:
              properties:
                state:
                  type: string
                  enum:
                  - "success"
                  - "failure"
                  - "error"
                  - "aborted"
          - required:
            - completionTime
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hook
  namespace: prow
  labels:
    app: hook
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: prow
      labels:
        app: hook
    spec:
      serviceAccountName: prow
      terminationGracePeriodSeconds: 180
      containers:
      - name: hook
        image: gcr.io/prometheus-test-204522/hook:v20180616-stat-235-g2de599c8c
        imagePullPolicy: Always
        args:
        - --dry-run=false
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
      - name: plugins
        configMap:
          name: plugins
      nodeSelector:
        isolation: prow
---
apiVersion: v1
kind: Service
metadata:
  name: hook
  namespace: prow
spec:
  selector:
    app: hook
  ports:
  - port: 8888
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plank
  namespace: prow
  labels:
    app: plank
spec:
  replicas: 1 # Do not scale up.
  template:
    metadata:
      namespace: prow
      labels:
        app: plank
    spec:
      serviceAccountName: prow
      containers:
      - name: plank
        image: gcr.io/k8s-prow/plank:v20180529-e9431eaa3
        args:
        - --dry-run=false
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
      nodeSelector:
        isolation: prow
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sinker
  namespace: prow
  labels:
    app: sinker
spec:
  replicas: 1
  template:
    metadata:
      namespace: prow
      labels:
        app: sinker
    spec:
      serviceAccountName: prow
      containers:
      - name: sinker
        image: gcr.io/k8s-prow/sinker:v20180529-e9431eaa3
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      nodeSelector:
        isolation: prow
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deck
  namespace: prow
  labels:
    app: deck
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: prow
      labels:
        app: deck
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: prow
      containers:
      - name: deck
        image: gcr.io/k8s-prow/deck:v20180529-e9431eaa3
        args:
        - --hook-url=http://hook:8888/plugin-help
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      nodeSelector:
        isolation: prow
---
apiVersion: v1
kind: Service
metadata:
  name: deck
  namespace: prow  
spec:
  selector:
    app: deck
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: horologium
  namespace: prow
  labels:
    app: horologium
spec:
  replicas: 1
  template:
    metadata:
      namespace: prow
      labels:
        app: horologium
    spec:
      serviceAccountName: prow
      terminationGracePeriodSeconds: 30
      containers:
      - name: horologium
        image: gcr.io/k8s-prow/horologium:v20180529-e9431eaa3
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      nodeSelector:
        isolation: prow
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing
  namespace: prow
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: deck
          servicePort: 80
      - path: /hook
        backend:
          serviceName: hook
          servicePort: 8888
---
# Acc to GKE docs, we need to make user cluster-admin before making RBAC roles
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  #This is for the service-account that will be used to deploy prombench
  #This is needed to make prometheus SD RBAC role & loadgen-scaler roles to grant access to scale deployments up and down
- kind: User
  name: "prow-test@prometheus-test-204522.iam.gserviceaccount.com"
  #This is for to grant access to prow components
- kind: User
  name: "system:serviceaccount:prow:prow"