{
 "title": "Prombench",
 "description": "Metrics useful for benchmarking and loadtesting Prometheus itself. Designed primarily for Prometheus 3.x.",
 "tags": [
  "benchmark",
  "node-metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RuleGroup",
    "query": "prometheus_rule_group_last_duration_seconds{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}"
   },
   { "name": "prNumber", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Acceptance: 💾 Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rate[10m] Go Heap Allocations (PR vs Ref: smaller, ideally negative, is better)",
   "type": "timeseries",
   "description": "Delta of number of bytes allocated per second (go_memstats_alloc_bytes_total), even if freed. PR minus Reference, so negative values indicate how much less PR allocates.\n\n10m lower than our periodic scrape load scale ups and downs cycles (~30m interval) but large enough to hide noise.",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - Allocated Bytes/s "
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}} - Allocated Bytes/s "
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ref % of Delta of number of bytes allocated per second (go_memstats_alloc_bytes_total), even if freed. PR minus Reference, so negative values indicate how much less PR allocates.\n",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))) / sum(rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - Allocated Bytes/s "
    }
   ]
  },
  {
   "title": "avg[10m] Allocations (PR vs Ref: smaller, ideally negative, is better)",
   "type": "timeseries",
   "description": "Delta of number of avg bytes allocated within 30m windows for RSS and heap.\n\nPR minus Reference, so negative values indicate how much less PR allocates.\n",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(avg_over_time(go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - Allocated (heap)"
    },
    {
     "expr": "sum(avg_over_time(process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(avg_over_time(process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - RSS"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}}- RSS"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ref % of Delta of number of avg bytes allocated within 30m windows for RSS and heap.\n\nPR minus Reference, so negative values indicate how much less PR allocates.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(avg_over_time(go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\", prometheus!~\"test-pr.*\"}[$__rate_interval])))/  sum(avg_over_time(go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - Allocated (heap)"
    },
    {
     "expr": "(sum(avg_over_time(process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(avg_over_time(process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))) / sum(avg_over_time(process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - RSS"
    }
   ]
  },
  { "title": "Acceptance: 💻 CPU ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "rate[10m] CPU (PR vs Ref: smaller, ideally negative, is better)",
   "type": "timeseries",
   "description": "Delta of per second process CPU usage.\n\nPR minus Reference, so negative values indicate how much less the PR use CPU.\n",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - rate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}} - rate"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ref % of Delta of per second process CPU usage.\n\nPR minus Reference, so negative values indicate how much less the PR use CPU.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\"}[$__rate_interval])) - sum(rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))) / sum(rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - rate"
    }
   ]
  },
  { "title": "Acceptance: 🧭 Query Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "rate[10m] Query Instant Latency (PR vs Ref: smaller, ideally negative, is better)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]))  - sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - {{handler}}"
    },
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\",handler=\"/api/v1/query\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\",handler=\"/api/v1/query\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}} - {{handler}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ref % of Delta of Query instant latency\n\nPR minus Reference, so negative values indicate how much less the PR use CPU.\n",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]))  - sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]))) / sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - {{handler}}"
    }
   ]
  },
  {
   "title": "rate[10m] Query Range Latency (PR vs Ref: smaller, ideally negative, is better)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]))  - sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - {{handler}}"
    },
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\",handler=\"/api/v1/query_range\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\",handler=\"/api/v1/query_range\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}} - {{handler}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ref % of Delta of Query range latency\n\nPR minus Reference, so negative values indicate how much less the PR use CPU.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]))  - sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]))) / sum by(handler) (rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\", prometheus!~\"test-pr.*\",handler=\"/api/v1/query_range\"}[$__rate_interval]))",
     "legendFormat": "PR vs Ref - {{handler}}"
    }
   ]
  },
  {
   "title": "Functional Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Version",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_build_info{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - {{version}} - {{revision}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Uptime"
      }
     ]
    },
    {
     "title": "Samples Appended/s",
     "type": "timeseries",
     "description": "This graph shows the sample ingested per second",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - samples/s"
      }
     ]
    },
    {
     "title": "Head Time series",
     "type": "timeseries",
     "description": "This graph indicates how many time series each instance holds",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Time series"
      }
     ]
    },
    {
     "title": "TSDB Reloads/s",
     "type": "timeseries",
     "description": "This graph shows the total number of times the database reloaded block data from disk",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_reloads_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Reloads"
      }
     ]
    },
    {
     "title": "Blocks Loaded",
     "type": "timeseries",
     "description": "Total Number of currently loaded data blocks",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Blocks Loaded"
      }
     ]
    },
    {
     "title": "TSDB Problems/s",
     "type": "timeseries",
     "description": "This graph shows various tsdb related checks",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_corruptions_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - WAL Corruptions"
      },
      {
       "expr": "rate(prometheus_tsdb_reloads_failures_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Reload Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_head_series_not_found{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Head Series Not Found"
      },
      {
       "expr": "rate(prometheus_tsdb_compactions_failed_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Compaction Failures"
      },
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Retention Cutoff Failures"
      }
     ]
    },
    {
     "title": "Compactions/s",
     "type": "timeseries",
     "description": "Total number of compactions that were executed for the partition",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compactions_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Compactions"
      }
     ]
    },
    {
     "title": "HTTP requests/s",
     "type": "timeseries",
     "description": "Step 61s is to avoid aliasing (max interval of our queries is 1m)",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - {{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "description": "Total number of bytes allocated, even if freed",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}} - Allocated Bytes/s"
    }
   ]
  },
  {
   "title": "Objects allocated per second",
   "type": "timeseries",
   "description": "Total number of objects allocated",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_gc_heap_allocs_objects_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}}"
    }
   ]
  },
  {
   "title": "Live objects on heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_gc_heap_objects_objects{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\"}",
     "legendFormat": "{{prometheus}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
     "legendFormat": "{{prometheus}} - Allocated"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}} - Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}} - 5m rate"
    }
   ]
  },
  {
   "title": "Avg HTTP request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_http_request_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Average GC duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\"}[$__rate_interval]) / rate(go_gc_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\"}[$__rate_interval]) ",
     "legendFormat": "{{prometheus}} - 10m rate"
    }
   ]
  },
  {
   "title": "GC runs per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"test-.*\"}[$__rate_interval]) *60",
     "legendFormat": "{{prometheus}} - 10m rate"
    }
   ]
  },
  {
   "title": "Avg Compaction Time/s",
   "type": "timeseries",
   "description": "Average compactions that were executed for the partition",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) / rate(prometheus_tsdb_compaction_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
     "legendFormat": "{{prometheus}}"
    }
   ]
  },
  {
   "title": "WAL Truncate Latency",
   "type": "timeseries",
   "description": "WAL is used to get the backup when the prometheus server crashes. WAL stores the last 2hrs of data in memory. After that it has to truncate the data. So, this graph shows the latency of truncation",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
     "legendFormat": "{{prometheus}} - Truncate Latency"
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Total memory"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"} - node_memory_MemFree_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"} - node_memory_Buffers_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"} - node_memory_Cached_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Used"
      },
      {
       "expr": "node_memory_Buffers_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Free"
      }
     ]
    },
    {
     "title": "Disk I/O Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\",device!~'^(md\\\\\\\\d+$|dm-)'}[$__rate_interval])",
       "legendFormat": "{{node}} - {{device}}"
      }
     ]
    },
    {
     "title": "Context Switches / Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(node_context_switches_total{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{node}} - Context Switches"
      },
      {
       "expr": "rate(node_intr_total{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{node}} - Interrupts"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{node=~'(test+).*',device!~'rootfs'})",
       "legendFormat": "{{node}} - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Load 1m"
      },
      {
       "expr": "node_load5{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Load 5m"
      },
      {
       "expr": "node_load15{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - Load 15m"
      }
     ]
    },
    {
     "title": "Filesystem Fullness",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - node_filesystem_free_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\",fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job=\"node-exporter\",namespace=\"prombench-${prNumber}\",node=~\"(test+).*\"}",
       "legendFormat": "{{node}} - {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Latency: Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg query engine timings/s - queue_time",
     "type": "timeseries",
     "description": "Time spent in queue_time mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"queue_time\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"queue_time\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}}"
      }
     ]
    },
    {
     "title": "Avg query engine timings/s - inner_eval",
     "type": "timeseries",
     "description": "Average Time spent in inner_eval mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"inner_eval\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"inner_eval\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}}"
      }
     ]
    },
    {
     "title": "Avg query engine timings/s - result_sort",
     "type": "timeseries",
     "description": "Average Time spent in result_sort mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"result_sort\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"result_sort\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}}"
      }
     ]
    },
    {
     "title": "Avg query engine timings/s - prepare_time",
     "type": "timeseries",
     "description": "Time spent in prepare_time mode, per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum{job=\"prometheus\",slice=\"prepare_time\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_engine_query_duration_seconds_count{job=\"prometheus\",slice=\"prepare_time\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Attic: Old panels, likely to remove",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "Total number open and maximum file descriptors of both release and PR",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_max_fds{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Max"
      },
      {
       "expr": "process_open_fds{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Open"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "timeseries",
     "description": "Chunks are the collection of series of samples. The active series is known as the head chunk. Total of 120 samples are present in a chunk. This graph shows the total head chunks",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Chunks"
      }
     ]
    },
    {
     "title": "Avg Head GC Time/s",
     "type": "timeseries",
     "description": "Average runtime of garbage collection in the head block",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_gc_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_tsdb_head_gc_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - GC Time/s"
      }
     ]
    },
    {
     "title": "Head Time Range",
     "type": "timeseries",
     "description": "Plots of minimum and maximum timestamp of the head block in reference to current time",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_min_time{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Min"
      },
      { "expr": "time() * 1000", "legendFormat": "Now" },
      {
       "expr": "prometheus_tsdb_head_max_time{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Max"
      }
     ]
    },
    {
     "title": "Head Active Appenders",
     "type": "timeseries",
     "description": "This graph shows the total number of active appender transactions",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}",
       "legendFormat": "{{prometheus}} - Head Appenders"
      }
     ]
    },
    {
     "title": "Rule Group: $RuleGroup",
     "type": "timeseries",
     "description": "Rule group describe the Prometheus alerts. These graph consist of two rules:\n- prometheus_rule_group_interval_seconds:  When the first notification was sent, wait for 'group_interval' to send a batch of new alerts that started firing for that group.\n- prometheus_rule_group_last_duration_seconds: It shows the last duration of each one of your groups in seconds\n",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
     "repeat": "RuleGroup",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_rule_group_interval_seconds{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\",rule_group=~\"$RuleGroup\"}\n",
       "legendFormat": "{{prometheus}} - Interval"
      },
      {
       "expr": "prometheus_rule_group_last_duration_seconds{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\",rule_group=~\"$RuleGroup\"}\n",
       "legendFormat": "{{prometheus}} - Last Duration"
      }
     ]
    },
    {
     "title": "Retention Cutoffs/s",
     "type": "timeseries",
     "description": "Total number of times the database cut off block data from disk",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_retention_cutoffs_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Retention Cutoffs"
      }
     ]
    },
    {
     "title": "Rule group evaluation problems/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_iterations_missed_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])  ",
       "legendFormat": "{{prometheus}} - Rule group missed"
      },
      {
       "expr": "rate(prometheus_rule_evaluation_failures_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Rule evals failed"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Time Range",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_range_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) / rate(prometheus_tsdb_compaction_chunk_range_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) or rate(prometheus_tsdb_compaction_chunk_range_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) / rate(prometheus_tsdb_compaction_chunk_range_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Chunk Time Range"
      }
     ]
    },
    {
     "title": "TSDB Isolation Watermarks",
     "type": "timeseries",
     "description": "This graph shows the highest and lowest TSDB watermarks. The highest watermark represents the latest appender and the lowest watermark represents the oldest appender",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_isolation_low_watermark{namespace='prombench-${prNumber}'}",
       "legendFormat": "{{prometheus}} - low watermark"
      },
      {
       "expr": "prometheus_tsdb_isolation_high_watermark{namespace='prombench-${prNumber}'}",
       "legendFormat": "{{prometheus}} - high watermark"
      }
     ]
    },
    {
     "title": "Evaluation time of rule groups/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Rule evaluation duration"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Chunk Samples",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) / rate(prometheus_tsdb_compaction_chunk_samples_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Chunk Samples"
      }
     ]
    },
    {
     "title": "Head Chunks Removed",
     "type": "timeseries",
     "description": "Head chunk is converted to chunk when it is filled with 120 samples. This graph shows the total number of head chunks created",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Removed"
      }
     ]
    },
    {
     "title": "First Compaction, Avg Bytes/Sample",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_compaction_chunk_size_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) or rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[$__rate_interval])",
       "legendFormat": "{{prometheus}} - Bytes/Sample"
      }
     ]
    },
    {
     "title": "TSDB Isolation Watermarks Difference",
     "type": "timeseries",
     "description": "This graph the difference of highest and lowest of TSDB watermark and also shows the size of isolation linked-chain",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_isolation_high_watermark{namespace='prombench-${prNumber}'} - prometheus_tsdb_isolation_low_watermark{namespace='prombench-${prNumber}'}",
       "legendFormat": "{{prometheus}}"
      }
     ]
    },
    {
     "title": "Head Chunks Created",
     "type": "timeseries",
     "description": "This graph shows chunks created per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Created"
      }
     ]
    },
    {
     "title": "WAL Fsync Latency",
     "type": "timeseries",
     "description": "The latency distributions of fsync called by wal. High fsync duration (fsync_durations_seconds) indicates disk issues and might cause the cluster to be unstable",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count{job=\"prometheus\",namespace=\"prombench-${prNumber}\",prometheus=~\"(test+).*\"}[1m])",
       "legendFormat": "{{prometheus}} - Fsync Latency"
      }
     ]
    }
   ]
  }
 ]
}